# Generated by Django 4.1.6 on 2023-02-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(null=True),
        ),
    ]
